name: Comparar versões dos Bots de Produção e Homologação

on:
  push:
    branches:
      - homolog  # Homologação
  pull_request:
    branches:
      - homolog

jobs:
  comparar-bots:
    runs-on: ubuntu-latest

    steps:
    # Fazer checkout da branch de produção (main)
    - name: Fazer checkout do bot de produção da main
      uses: actions/checkout@v4
      with:
        ref: main  # Faz o checkout da branch de produção (main)

    # Mover o arquivo de produção para um local temporário
    - name: Salvar o bot de produção em local temporário
      run: mv bots/export_builder_prod.json /tmp/export_builder_prod.json

    # Fazer checkout da branch de homologação (homolog)
    - name: Fazer checkout do bot de homologação
      uses: actions/checkout@v4
      with:
        ref: homolog  # Faz o checkout da branch de homologação (homolog)

    # Recuperar o arquivo de produção do local temporário para o diretório de trabalho
    - name: Recuperar o bot de produção
      run: mv /tmp/export_builder_prod.json ./export_builder_prod.json

    # Copiar o arquivo de homologação para o diretório de trabalho
    - name: Copiar bot de homologação para o diretório de trabalho
      run: cp bots/export_builder_homolog.json ./export_builder_homolog.json

    # Instalar Node.js
    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Instalar dependências do projeto
    - name: Instalar dependências
      run: npm install

    # Executar o script de comparação dos bots
    - name: Executar script de comparação dos bots
      run: node compareBots.js

    # Fazer upload do resultado da comparação
    - name: Enviar resultado da comparação
      uses: actions/upload-artifact@v4
      with:
        name: bot-comparison-prod-vs-homolog
        path: |
          bots/bot_comparison_prod_vs_homolog.json
          bots/bot_normalized_1.json
          bots/bot_normalized_2.json

    # Listar arquivos após a mudança de branch
    - name: Listar arquivos após a execução do compareBots
      run: ls -la bots

    # Mover o arquivo de comparação para um local temporário
    - name: Salvar o resultado da comparação em local temporário
      run: mv bots/* /tmp/ #mv bots/bot_comparison_prod_vs_homolog.json /tmp/bot_comparison_prod_vs_homolog.json

    # Fazer checkout da branch de páginas (gh-pages)
    - name: Fazer checkout da branch gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages  # Faz o checkout da branch de páginas (gh-pages)

    # Recuperar o arquivo de comparação para o diretório de trabalho
    - name: Recuperar o resultado da comparação
      run: |
        if test -f /tmp/bot_comparison_prod_vs_homolog.json; then mv /tmp/bot_comparison_prod_vs_homolog.json ./bot_comparison_prod_vs_homolog.json; fi
        if test -f /tmp/bot_normalized_1.json; then mv /tmp/bot_normalized_1.json ./bot_normalized_1.json; fi
        if test -f /tmp/bot_normalized_2.json; then mv /tmp/bot_normalized_2.json ./bot_normalized_2.json; fi
      # mv /tmp/bot_comparison_prod_vs_homolog.json ./bot_comparison_prod_vs_homolog.json
    
    # Listar arquivos após a mudança de branch
    - name: Listar arquivos após a mudança de branches
      run: ls -la
