name: Compara as versões dos Bots em Produção e Homologação

on:
  push:
    branches:
      - main  # Produção
      - homolog  # Homologação
  pull_request:
    branches:
      - main
      - homolog

jobs:
  compare-bots:
    runs-on: ubuntu-latest

    steps:
    # Checkout da branch de produção (main)
    - name: Check out production bot from main
      uses: actions/checkout@v4
      with:
        ref: main  # Faz o checkout da branch de produção (main)

    # Mover o arquivo de produção para um local temporário
    - name: Save production bot
      run: mv bots/export_builder_prod.json /tmp/export_builder_prod.json

    # Checkout da branch de homologação (homolog)
    - name: Check out staging bot from homolog
      uses: actions/checkout@v4
      with:
        ref: homolog  # Faz o checkout da branch de homologação (homolog)

    # Mover o arquivo de produção de volta para o diretório de trabalho
    - name: Retrieve production bot
      run: mv /tmp/export_builder_prod.json ./export_builder_prod.json

    # Copiar o arquivo de homologação para o diretório de trabalho
    - name: Copy staging bot
      run: cp bots/export_builder_homolog.json ./export_builder_homolog.json

    # Instalar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Instalar dependências
    - name: Install dependencies
      run: npm install

    # Executar o script de comparação
    - name: Run bot comparison script
      run: node compareBots.js

    # Fazer upload do resultado da comparação
    - name: Upload comparison result
      uses: actions/upload-artifact@v4
      with:
        name: bot-comparison-prod-vs-homolog
        path: bot_comparison_prod_vs_homolog.json
    
    # mostra diretorio
    - name: List files in bots directory
      run: ls -la /home/runner/work/bots-comparison/bots-comparison/bots

    # Faz o commit do arquivo na branch gh-pages
    - name: Commit comparison result
      run: |
        git config --local user.email "mrccunha@gmail.com"
        git config --local user.name "Mauro Cunha"
        git add /home/runner/work/bots-comparison/bots-comparison/bots/bot_comparison_prod_vs_homolog.json
        git commit -m "Adiciona resultado da comparação entre bots de produção e homologação"
        git push origin homolog
