name: Compare Production and Staging Bots

on:
  push:
    branches:
      - main  # Produção
      - homolog  # Homologação
  pull_request:
    branches:
      - main
      - homolog

jobs:
  compare-bots:
    runs-on: ubuntu-latest

    steps:
    # Checkout do arquivo de produção na branch main
    - name: Check out production bot from main
      uses: actions/checkout@v4
      with:
        ref: main  # Faz o checkout da branch de produção
    - name: Copy production bot
      run: cp bots/export_builder_prod.json ./export_builder_prod.json

    # Checkout do arquivo de homologação na branch homolog
    - name: Check out staging bot from homolog
      uses: actions/checkout@v4
      with:
        ref: homolog  # Faz o checkout da branch de homologação
    - name: Copy staging bot
      run: cp bots/export_builder_homolog.json ./export_builder_homolog.json

    # Instalar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Instalar dependências
    - name: Install dependencies
      run: npm install

    # Executar o script de comparação
    - name: Run bot comparison script
      run: node compareBots.js

    # Fazer upload do resultado da comparação
    - name: Upload comparison result
      uses: actions/upload-artifact@v4
      with:
        name: bot-comparison-prod-vs-homolog
        path: bot_comparison_prod_vs_homolog.json
